language: node_js
node_js:
  - '8'
  - '9'
before_install:
  - npm i -g npm@6
install:
  - npm install
  - npm i --no-save git+https://github.com/discordjs/discord.js.git
script: bash ./travis/test.sh
jobs:
  include:
  - stage: deploy
    node_js: 9
    script: bash ./travis/deploy.sh
    env:
    - ENCRYPTION_LABEL="d9d8d4fbc4cd"
    - COMMIT_AUTHOR_EMAIL="admin@opposite.biz"
cache:
  directories:
  - node_modules
dist: trusty
sudo: false
